version: '3.4'

services:
  teamcity:
    image: jetbrains/teamcity-server:2020.2.3
    ports:
      - "8112:8111"
    volumes:
      - E:/Dev/EStore-volumes/data_dir:/data/teamcity_server/datadir
      - E:/Dev/EStore-volumes/log_dir:/opt/teamcity/logs
  teamcity-agent-1:
    image: jetbrains/teamcity-agent:2020.2.3
    privileged: true
    volumes:
      - E:/Dev/EStore-volumes/agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      - AGENT_NAME="Agent 1"
      - SERVER_URL=http://teamcity:8111
      - DOCKER_IN_DOCKER=start